### ISSUE TITLE
Add a function to return the array of validators

### ISSUE THREAD

**Issue by come-maiz** [TPL-protocol/tpl-contracts#2]
On the dapp, we want to show the addresses of the validators. For now, we are doing it inspecting the blockchain for the `ValidatorAdded` events (see #1), but that is too slow.

It would be better to have a function that returns all the validators.

**Comment by 0age** [comment]
This is now supported by calling `getAvailableValidators`, or `countAvailableValidators` followed by `getAvailableValidator(uint256 _index)` in cases where the dynamic array returned by `getAvailableValidators` is too large. From there, additional information about a validator at a given address can be retrieved by calling `getValidatorInformation(address _validator)`.
