### ISSUE TITLE
Publish the contracts to npm

### ISSUE THREAD

**Issue by come-maiz** [TPL-protocol/tpl-contracts#3]
We are writing the dapp that will consume these contracts, and it would be easier to do it with the contracts released to npm. Then we could add them as a dependency instead of copying or linking them.

**Comment by 0age** [comment]
Packages can now be added as a dependency using:
```sh
$ npm install tpl-contracts
```
or:
```sh
$ yarn add tpl-contracts
```
Additionally, there is now an npm badge in the Readme file.
